### ISSUE TITLE
About the bundle adjustment

### ISSUE THREAD

**Issue by ljjTYJR** [NPU-YanChi/diff-gaussian-rasterization-for-gsslam#2]
Hi authors,

I have a minor question on the "Bundle Adjustment" in the paper.
Did you conduct the ablation study on bundle adjustment? I ever tried some simple experiments, which show the bundle adjustment makes the result worse.

I wonder did you do experiments on it? Do you have some observations during the process?

Best,
Shuo.

**Comment by yanchi-3dv** [comment]
We have not done an ablation study on bundle adjustment yet.
In our experiment, if the 3DGS is incorrect, the pose estimation will be wrong, so we only optimize it after 1/2 iters.
Even if we only optimize it after 1/2 iters, sometimes it still makes a worse result.
The motivation why for BA is to make sure the 3DGS perspective is consistent.
