### ISSUE TITLE
What is the difference between tracking and mapping mode?

### ISSUE THREAD

**Issue by TwiceMao** [NPU-YanChi/diff-gaussian-rasterization-for-gsslam#3]
@NPU-YanChi   Thank you for your excellent work. What is the difference between tracking and mapping mode? Will it affect the gradient of the rendered color map and the rendered depth?

**Comment by TwiceMao** [comment]
I also want to ask, compared with the original rendering code, will it take up much more GPU memory? If so, approximately how much?

**Comment by yanchi-3dv** [comment]
1. In tracking mode, I disable some intermediate variable need by cal camera pose, so it can save some time.
2. The forward pass is basically consistent with volume rendering, which is common used in NeRF based Depth rendering. However, note that Dynamic3DGaussians use median depth.
3. Compared with the original rendering code, I think it would not take up much more GPU memory, maybe a very slight increase. I didn't test for that.

**Comment by TwiceMao** [comment]
Thx！
