### ISSUE TITLE
cooperative_groups/reduce.h: No such file or directory

### ISSUE THREAD

**Issue by Lcp9202** [NPU-YanChi/diff-gaussian-rasterization-for-gsslam#4]
The error prompt shown as: 
cuda_rasterizer/backward.cu:15:10: fatal error: cooperative_groups/reduce.h: No such file or directory
 #include <cooperative_groups/reduce.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit code 1

The CUDA version I used is 10-1. When I list the path of "/usr/local/cuda-10.1/include", I only find the "cooperative_groups.h" instead of the folder. When I excuate the command of "find /usr/local/cuda-10.1/ -name reduce.h", the "reduce.h" only was included in the folder of "thrust".

**Comment by yanchi-3dv** [comment]
Sry for the late reply. We are using CUDA version 11.3. It might be helpful to update your CUDA installation to this version and see if that resolves the issue.
